version: 2

jobs:
  test:
    docker:
      - image: cimg/rust:1.59

    steps:
      - checkout

      - run:
          name: Change Permissions for Cargo Cache
          command: |
            if [ -d "/usr/local/cargo" ]; then
              sudo chown -R circleci:circleci /usr/local/cargo
            fi
      - restore_cache:
          key: stable-cache-v1-{{ checksum "Cargo.toml" }}

      - run:
          name: Show Version
          command: |
            rustc --version --verbose
            rustup --version
            cargo --version --verbose
      - run:
          name: Run Tests
          command: cargo test

      - save_cache:
          key: stable-cache-v1-{{ checksum "Cargo.toml" }}
          paths:
            - "~/.cargo/"
            - "~/.rustup/"
            - "./target"
            - "/usr/local/cargo"

workflows:
  version: 2
  test:
    jobs:
      - test
